<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="kli.Localize" Version="2.0.4" />

        <Localize Include="Localizations\Locale_*.json" ClassName="MyLocale" NeutralCulture="de" />
    </ItemGroup>

</Project>
