<?xml version="1.0" encoding="utf-8" ?>
<Project>
    <ItemGroup>
        <CompilerVisibleProperty Include="Localize" />
        <CompilerVisibleItemMetadata Include="Localize" MetadataName="NamespaceName"/>
        <CompilerVisibleItemMetadata Include="Localize" MetadataName="ClassName"/>
        <CompilerVisibleItemMetadata Include="Localize" MetadataName="NeutralCulture"/>
        <CompilerVisibleItemMetadata Include="AdditionalFiles" MetadataName="LocalizeFile"/>
    </ItemGroup>
</Project>