name: 'CI\CD'

on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.setOutputs.outputs.tag }} 
    
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: kli.Localize.v${{ env.GitBuildVersionSimple }}.nupkg
        path: src/kli.Localize.Generator/bin/Release/*.nupkg
    - name: Set job outputs
      id: setOutputs
      run: echo "::set-output name=tag::v${{ env.GitBuildVersionSimple }}"
  
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: kli.Localize.${{ needs.build.outputs.tag }}.nupkg
        path: artifacts
    - name: Create github release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: "${{ needs.build.outputs.tag }}"
        files: |
          artifacts/*.nupkg
    - name: Publish the package to nuget.org
      run: dotnet nuget push artifacts/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
    env:
      NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
